# Ejercicio 3

### Importación de librerías

In [1]:
import duckdb
import pandas as pd
from pathlib import Path

### Rutas de archivos

In [2]:
RUTA_YELLOW = "../data/raw/yellow/2026/*.parquet"
RUTA_GREEN = "../data/raw/green/2026/*.parquet"

### Conexión de DuckDB

In [3]:
con = duckdb.connect()

### 3.1) Cantidad de archivos disponibles

In [7]:
archivos_yellow = list(Path('../data/raw/yellow/2026').glob("*.parquet"))
archivos_green = list(Path('../data/raw/green/2026').glob("*.parquet"))

print("Archivos de taxis amarillos:", len(archivos_yellow))
print("Archivos de taxis verdes:", len(archivos_green))
print("Total de archivos:", len(archivos_yellow) + len(archivos_green))

Archivos de taxis amarillos: 8
Archivos de taxis verdes: 8
Total de archivos: 16

### 3.2) Cantidad de registros disponibles

In [14]:
query = Path("../sql/ejercicio_3_2_a.sql").read_text()
registros_yellow = con.execute(query).fetchone()[0]

query = Path("../sql/ejercicio_3_2_b.sql").read_text()
registros_green = con.execute(query).fetchone()[0]

print("Registros de taxis amarillos:", registros_yellow)
print("Registros de taxis verdes:", registros_green)
print("Total de registros:", registros_yellow + registros_green)

Registros de taxis amarillos: 29703355
Registros de taxis verdes: 337114
Total de registros: 30040469

### 3.3) Columnas disponibles
### 3.4) Tipos de datos

In [15]:
query = Path("../sql/ejercicio_3_3_a.sql").read_text()
columnas_yellow = con.execute(query).df()

columnas_yellow

              column_name column_type null   key default extra
0                VendorID     INTEGER  YES  None    None  None
1    tpep_pickup_datetime   TIMESTAMP  YES  None    None  None
2   tpep_dropoff_datetime   TIMESTAMP  YES  None    None  None
3         passenger_count      BIGINT  YES  None    None  None
4           trip_distance      DOUBLE  YES  None    None  None
5              RatecodeID      BIGINT  YES  None    None  None
6      store_and_fwd_flag     VARCHAR  YES  None    None  None
7            PULocationID     INTEGER  YES  None    None  None
8            DOLocationID     INTEGER  YES  None    None  None
9            payment_type      BIGINT  YES  None    None  None
10            fare_amount      DOUBLE  YES  None    None  None
11                  extra      DOUBLE  YES  None    None  None
12                mta_tax      DOUBLE  YES  None    None  None
13             tip_amount      DOUBLE  YES  None    None  None
14           tolls_amount      DOUBLE  YES  None    None  None
15  improvement_surcharge      DOUBLE  YES  None    None  None
16           total_amount      DOUBLE  YES  None    None  None
17   congestion_surcharge      DOUBLE  YES  None    None  None
18            Airport_fee      DOUBLE  YES  None    None  None
19     cbd_congestion_fee      DOUBLE  YES  None    None  None

In [16]:
query = Path("../sql/ejercicio_3_3_b.sql").read_text()
columnas_green = con.execute(query).df()

columnas_green

              column_name column_type null   key default extra
0                VendorID     INTEGER  YES  None    None  None
1    lpep_pickup_datetime   TIMESTAMP  YES  None    None  None
2   lpep_dropoff_datetime   TIMESTAMP  YES  None    None  None
3      store_and_fwd_flag     VARCHAR  YES  None    None  None
4              RatecodeID      BIGINT  YES  None    None  None
5            PULocationID     INTEGER  YES  None    None  None
6            DOLocationID     INTEGER  YES  None    None  None
7         passenger_count      BIGINT  YES  None    None  None
8           trip_distance      DOUBLE  YES  None    None  None
9             fare_amount      DOUBLE  YES  None    None  None
10                  extra      DOUBLE  YES  None    None  None
11                mta_tax      DOUBLE  YES  None    None  None
12             tip_amount      DOUBLE  YES  None    None  None
13           tolls_amount      DOUBLE  YES  None    None  None
14              ehail_fee      DOUBLE  YES  None    None  None
15  improvement_surcharge      DOUBLE  YES  None    None  None
16           total_amount      DOUBLE  YES  None    None  None
17           payment_type      BIGINT  YES  None    None  None
18              trip_type      BIGINT  YES  None    None  None
19   congestion_surcharge      DOUBLE  YES  None    None  None
20     cbd_congestion_fee      DOUBLE  YES  None    None  None

3.3)  
Los taxis verdes tiene 2 columnas extras: **ehail_fee** y **trip_type**. Los taxis amarillos tienen una columna extra **Airport_fee**.  
Las dos variables de tipo Timestamp difieren en nombre en ambos conjuntos de datos, solo en la primera letra.  

3.4)  
- Los dos conjuntos tienen dos variables TIMESTAMP.
- Los dos conjuntos tienen las mismas 3 variables INTEGER.
- Los dos conjuntos tienen las mismas 3 variables BIGINT, adicional los taxis verdes tienen una variable más del tipo BIGINT **trip_type**.
- Los dos conjuntos tienen la misma variable VARCHAR.
- Los dos conjuntos tienen las mismas 10 variables DOUBLE, adicional los taxis verdes tienen una variable más del tipo DOUBLE **ehail_fee** y los taxis amarillos tienen **Airport_fee**.

### 3.5) Muestras de los conjuntos de datos

In [17]:
query = Path("../sql/ejercicio_3_5_a.sql").read_text()
muestra_yellow = con.execute(query).df()

muestra_yellow

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1,0.97,1,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0,0.90,1,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0,1.40,1,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4,5.58,1,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0,2.16,1,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [18]:
query = Path("../sql/ejercicio_3_5_b.sql").read_text()
muestra_green = con.execute(query).df()

muestra_green

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,1,2026-01-01 00:27:58,2026-01-01 00:55:16,N,1,65,233,2,6.20,31.7,...,1.5,7.5,0.0,NaN,1.0,45.20,1,1,2.75,0.75
1,2,2026-01-01 00:44:33,2026-01-01 01:32:56,N,5,66,188,5,5.36,50.0,...,0.0,10.2,0.0,NaN,1.0,61.20,1,2,0.00,0.00
2,1,2026-01-01 00:23:45,2026-01-01 00:45:03,N,1,65,179,4,10.60,41.5,...,1.5,2.0,0.0,NaN,1.0,46.00,1,1,0.00,0.00
3,1,2026-01-01 00:44:33,2026-01-01 01:00:45,N,1,42,141,1,4.20,19.8,...,1.5,0.0,0.0,NaN,1.0,25.05,2,1,2.75,0.00
4,2,2026-01-01 00:46:04,2026-01-01 01:04:40,N,1,95,82,1,2.76,19.1,...,0.5,0.0,0.0,NaN,1.0,21.60,2,1,0.00,0.00

### 3.6) Posibles problemas de calidad de datos durante el análisis exploratorio
### 3.7) Consultas SQL
### 3.8) Documentación

##### Valores nulos, distancias o montos negativos, fechas inconsistentes y cantidades de pasajeros sospechosas.

In [20]:
calidad_yellow = con.execute(f"""
    SELECT
        COUNT(*) AS total_registros,
        COUNT(*) FILTER (WHERE passenger_count IS NULL) AS passenger_count_null,
        COUNT(*) FILTER (WHERE trip_distance IS NULL) AS trip_distance_null,
        COUNT(*) FILTER (WHERE trip_distance < 0) AS trip_distance_negativa,
        COUNT(*) FILTER (WHERE passenger_count < 0) AS passenger_count_negativo,
        COUNT(*) FILTER (WHERE tpep_dropoff_datetime < tpep_pickup_datetime) AS fechas_inconsistentes
    FROM read_parquet('{RUTA_YELLOW}')
""").df()

calidad_yellow

,total_registros,passenger_count_null,trip_distance_null,trip_distance_negativa,passenger_count_negativo,fechas_inconsistentes
0,29703355,7716688,0,0,0,10

$\textbf{Documentación}$